# Generated by Django 5.0.3 on 2024-04-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0003_generatedimage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerfolder",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
