# Generated by Django 5.0.3 on 2024-04-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0004_layerfolder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerfolder",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="layers_images/"),
        ),
    ]
