# Generated by Django 5.0.3 on 2024-05-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0005_layerfolder_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layerfolder",
            name="image",
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="ipfs_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="layerfolder",
            name="ipfs_image_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
