# Generated by Django 5.0.3 on 2024-05-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0006_remove_layerfolder_image_generatedimage_ipfs_hash_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generatedimage",
            options={
                "verbose_name": "Generated Image",
                "verbose_name_plural": "Generated Images",
            },
        ),
        migrations.RenameField(
            model_name="generatedimage",
            old_name="ipfs_hash",
            new_name="token_id",
        ),
        migrations.RemoveField(
            model_name="generatedimage",
            name="image",
        ),
    ]
