# Generated by Django 5.0.3 on 2024-05-15 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0007_alter_generatedimage_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_images", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="ipfs_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_images", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="token_uri",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
