# Generated by Django 5.0.3 on 2024-05-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0008_generatedimage_dislikes_generatedimage_ipfs_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="tx_hash",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
