# Generated by Django 5.0.3 on 2024-05-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0009_generatedimage_tx_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layerfolder",
            name="ipfs_image_hash",
        ),
        migrations.AddField(
            model_name="layerfolder",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="layer_folders/"),
        ),
    ]
