# Generated by Django 5.0.3 on 2024-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0011_remove_layerfolder_image_layerfolder_ipfs_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="owner_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
