# Generated by Django 5.0.3 on 2024-06-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0012_generatedimage_owner_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=18, null=True
            ),
        ),
    ]
