# Generated by Django 5.0.3 on 2024-06-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0018_alter_generatedimage_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedimage",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0.001, max_digits=36),
        ),
    ]
