# Generated by Django 5.0.3 on 2024-06-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0019_alter_generatedimage_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
