# Generated by Django 5.0.3 on 2024-06-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0020_apiprofile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiprofile",
            name="communities_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apiprofile",
            name="discussions_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apiprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apiprofile",
            name="reviews_count",
            field=models.IntegerField(default=0),
        ),
    ]
