# Generated by Django 5.0.3 on 2024-06-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0023_alter_apiprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="image/user.png",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
