# Generated by Django 4.2 on 2024-06-13 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0025_remove_apiprofile_user_apiprofile_api_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiprofile',
            name='api_profile',
        ),
        migrations.AddField(
            model_name='apiprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
